### ISSUE TITLE
Support Chinese Aliyun OSS or Qiniu Cloud Storage

### ISSUE THREAD

**Issue by krisoul** [qor/oss#1]
Hello,

So lucky to use your qor tool suites, but it seems not very compatible with Chinese, will you guys support Aliyun OSS or Qiniu Cloud Storage somedays in the future, because the two are the most common used in China for storing files.

Appreciated, thx :smiling_imp:

**Comment by jinzhu** [comment]
Yes, we will support that, and pull request is welcome ;)

**Comment by jinzhu** [comment]
Qiniu is supported in this commit https://github.com/qor/oss/commit/af74452c7bf9d85a37aad3f36a1ad3345fe21698

**Comment by krisoul** [comment]
thx, dear

**Comment by jinzhu** [comment]
Aliyun supported also.
